replicaCount: 2

image:
  repository: ghcr.io/namdp-it/my-app
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "nginx"
  host: "my-app-local"
